import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <h1>Hello World</h1>
        <h1>Example heading <span className="badge text-bg-secondary">New</span></h1>
        <h2>Example heading <span className="badge text-bg-secondary">New</span></h2>
        <h3>Example heading <span className="badge text-bg-secondary">New</span></h3>
        <h4>Example heading <span className="badge text-bg-secondary">New</span></h4>
        <h5>Example heading <span className="badge text-bg-secondary">New</span></h5>
        <h6>Example heading <span className="badge text-bg-secondary">New</span></h6>
      </div>
      <button type="button" className="btn btn-primary">
        Notifications <span className="badge text-bg-secondary">4</span>
      </button>
    </>
  );
}
